# samples file
samples_csv: "config/samples.csv"
## choose an integer for bp
binSize: 50
## number of processors
numberOfProcessors: 8
## before or after region start length for count matrix; integer bp
beforeRegionStartLength: 4000
afterRegionStartLength: 4000
# heat plot options
colorsForHeatPlot: "#543005,#f5f5f5,#003c30"
heatplotBreaks: "-1,0,1"
## dimensions of pdf in inches
pdfWidth: 2
pdfHeight: 4
## Deeptools Heatplot Options
referencePointLabel: "Peak midpoint"
regionsLabel: "Peaks"
xAxisLabel: "Distance from midpoint (bp)"
heatMapHeight: 100
headMapWidth: 10

#################################################################
##                     Environment Modules                     ##
#################################################################
# These will be specific to your cluster                        #
#################################################################
deeptools: "deeptools/3.4.3"
R: "R/4.1.2-mkl"
Bioconductor: "bioconductor/3.14"
